name: "SyncSilo Hosting"
on:
  push:
    paths:
      - "src/**"
      - "firebase.json"
      - "public/**"
      - "index.html"
      - "package.json"
    branches:
      - "dev"
      
  pull_request:
    types: [closed]
    branches: [main]
    
  workflow_dispatch:
    
jobs:

  beta_preview:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == github.triggering_actor && github.ref_name == 'dev' }}
    steps:
      - name: "Checkout to the branch"
        uses: actions/checkout@v3
      - name: "Node.js setup"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install Dependencies (Clean)"
        run: npm ci
      - name: "Build the project"
        run: npm run build
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelID: beta
          target: syncsilo-57b5e
          expires: 2d
          projectID: anweshan-cybrix

  live_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.ref_name == 'main') }}
    steps:
      - name: "Checkout to the branch"
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: "Node.js setup"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install Dependencies (Clean)"
        run: npm ci
      - name: "Build the project"
        run: npm run build
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelID: live
          target: syncsilo-57b5e
          projectID: anweshan-cybrix
